version: '3'
services:
  wp:
    build: .
    # image: "randyjp/rfpselect-wp"
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_PASSWORD: qwerty
    volumes: 
      - ./wp-content/config:/var/www/html/wp-content/config
      - ./acf-json:/var/www/html/wp-content/themes/twentyseventeen/acf-json
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - rfpselect-datavolume:/var/lib/mysql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=rfp-select-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  rfpselect-datavolume:
  esdata1:


networks:
  default:
    external:
      name: rfpselect-network