version: '3'
services:
  wp:
    build: .
    # image: "randyjp/rfpselect-wp"
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_PASSWORD: qwerty
    volumes: 
      - ./wp-content/config:/var/www/html/wp-content/config
      - ./acf-json:/var/www/html/wp-content/themes/twentyseventeen/acf-json
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - rfpselect-datavolume:/var/lib/mysql
volumes:
  rfpselect-datavolume: