apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-backend-dev
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: rfpselect
        role: backend
        env: canary
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - image: us.gcr.io/rfpselectdev/rfpselect-wp:1.0.0
          name: wordpress
          env:
            - name: "WORDPRESS_DB_HOST"
              value: "127.0.0.1:3306"
            - name: "WORDPRESS_DB_PASSWORD"
              value: "qwerty987"
        - image: mysql:5.7
          name: mysql
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: "qwerty987"
          volumeMounts:
            - name: rfpselect-datavolume
              mountPath: /var/lib/mysql
              subPath: db
        - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
          name: elasticsearch
          ports:
          - containerPort: 9200
          env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              value: rfp-select-cluster
          volumeMounts:
            - name: esdata1
              mountPath: /usr/share/elasticsearch/data
              subPath: es
      volumes:
      - name: rfpselect-datavolume
        persistentVolumeClaim:
          claimName: rfpselect-datavolume
      - name: esdata1
        persistentVolumeClaim:
          claimName: esdata1
      

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfpselect-datavolume
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata1
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 500Mi