kind: Service
apiVersion: v1
metadata:
  name: rfpselect-wp-backend
spec:
  type: LoadBalancer
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
    protocol: TCP
  - name: "elasticsearch"
    port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: rfpselect
    role: backend 