kind: Service
apiVersion: v1
metadata:
  name: rfpselect-wp
spec:
  type: LoadBalancer
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    app: rfpselect
    role: backend 