kind: Service
apiVersion: v1
metadata:
  name: es-service
  labels:
    service: elasticsearch
spec:
  type: LoadBalancer 
  ports:
  - name: "serving"
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: "node-to-node"
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    service: elasticsearch